DROP TABLE IF EXISTS BOOKS;
CREATE TABLE BOOKS(ID BIGINT PRIMARY KEY AUTO_INCREMENT, NAME VARCHAR(255), AUTHOR_ID BIGINT, GENRE_ID BIGINT);
DROP TABLE IF EXISTS authors;
CREATE TABLE authors(ID BIGINT PRIMARY KEY AUTO_INCREMENT, FIRST_NAME VARCHAR(255), LAST_NAME VARCHAR(255));
DROP TABLE IF EXISTS genres;
CREATE TABLE genres(ID BIGINT PRIMARY KEY AUTO_INCREMENT, NAME VARCHAR(255));