DROP TABLE IF EXISTS books;
CREATE TABLE books(ID BIGINT PRIMARY KEY AUTO_INCREMENT, NAME VARCHAR(255), AUTHOR_ID BIGINT, GENRE_ID BIGINT);
DROP TABLE IF EXISTS authors;
CREATE TABLE authors(ID BIGINT PRIMARY KEY AUTO_INCREMENT, FIRST_NAME VARCHAR(255), LAST_NAME VARCHAR(255));
DROP TABLE IF EXISTS genres;
CREATE TABLE genres(ID BIGINT PRIMARY KEY AUTO_INCREMENT, NAME VARCHAR(255));

ALTER TABLE authors
    ADD CONSTRAINT uq_author UNIQUE(FIRST_NAME, LAST_NAME);

ALTER TABLE genres
    ADD CONSTRAINT uq_genre UNIQUE(NAME);